<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Precios.aspx.cs" Inherits="WebApplication6.Precios" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <article id="content">
				<h2 class="header-a">Our price list:</h2>
				<ul class="gallery-b">
					<li><span class="strong">Simple wedding menu</span> <span class="price">18<span>€</span> <span>per person</span></span> <span class="i">Autem vel eum iriure dolor in hendrerit</span> Vulputate velit <a href="./">esse molestie consequat</a>, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim lorem qui ut wisi enim ad minim veniam, quis nostrud exerci tation.</li>
					<li><span class="strong">Simple wedding menu</span> <span class="price">18<span>€</span> <span>per person</span></span> <span class="i">Autem vel eum iriure dolor in hendrerit</span> Vulputate velit <a href="./">esse molestie consequat</a>, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim lorem qui ut wisi enim ad minim veniam, quis nostrud exerci tation.</li>
					<li><span class="strong">Simple wedding menu</span> <span class="price">18<span>€</span> <span>per person</span></span> <span class="i">Autem vel eum iriure dolor in hendrerit</span> Vulputate velit <a href="./">esse molestie consequat</a>, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim lorem qui ut wisi enim ad minim veniam, quis nostrud exerci tation.</li>
					<li><span class="strong">Simple wedding menu</span> <span class="price">18<span>€</span> <span>per person</span></span> <span class="i">Autem vel eum iriure dolor in hendrerit</span> Vulputate velit <a href="./">esse molestie consequat</a>, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim lorem qui ut wisi enim ad minim veniam, quis nostrud exerci tation.</li>
					<li><span class="strong">Simple wedding menu</span> <span class="price">18<span>€</span> <span>per person</span></span> <span class="i">Autem vel eum iriure dolor in hendrerit</span> Vulputate velit <a href="./">esse molestie consequat</a>, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim lorem qui ut wisi enim ad minim veniam, quis nostrud exerci tation.</li>
					<li><span class="strong">Simple wedding menu</span> <span class="price">18<span>€</span> <span>per person</span></span> <span class="i">Autem vel eum iriure dolor in hendrerit</span> Vulputate velit <a href="./">esse molestie consequat</a>, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim lorem qui ut wisi enim ad minim veniam, quis nostrud exerci tation.</li>
					<li><span class="strong">Simple wedding menu</span> <span class="price">18<span>€</span> <span>per person</span></span> <span class="i">Autem vel eum iriure dolor in hendrerit</span> Vulputate velit <a href="./">esse molestie consequat</a>, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim lorem qui ut wisi enim ad minim veniam, quis nostrud exerci tation.</li>
					<li><span class="strong">Simple wedding menu</span> <span class="price">18<span>€</span> <span>per person</span></span> <span class="i">Autem vel eum iriure dolor in hendrerit</span> Vulputate velit <a href="./">esse molestie consequat</a>, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim lorem qui ut wisi enim ad minim veniam, quis nostrud exerci tation.</li>
					<li><span class="strong">Simple wedding menu</span> <span class="price">18<span>€</span> <span>per person</span></span> <span class="i">Autem vel eum iriure dolor in hendrerit</span> Vulputate velit <a href="./">esse molestie consequat</a>, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim lorem qui ut wisi enim ad minim veniam, quis nostrud exerci tation.</li>
				</ul>
				<p class="link-a"><a href="./">Download our price list and our menus</a></p>
			</article>
</asp:Content>
